import Provider from "@/components/Provider";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "@rainbow-me/rainbowkit/styles.css";

// Others

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={`${inter.className}`}>
        <Provider>
          <Header />
          {children}
          <Footer />
          {/* <Footer /> */}
        </Provider>
      </body>
    </html>
  );
}
