import Provider from "@/components/Provider";
import { Inter } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "../context/change-mode";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";

// Others

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={`${inter.className}`}>
        <ThemeProvider>
          <Provider>
            <Header />
            {children}
            <Footer />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
